### ISSUE TITLE
Odoo 14 Commented Addons

### ISSUE THREAD

**Issue by kamarya** [lefilament/odoo_docker#2]
I see in `14.0.Dockerfile` that a few add-ons have been skipped and commented out because you are waiting for them to be ported to 14.0.

Please check them again cause some of them at least have been ported and therefore you should let them in the image.

**Comment by yboujraf** [comment]
Dear @remi-filament , @kamarya 

When adding some addons, most of the time some dependencies are missing and need pip install requirements.txt and/or need to install other dependencies.
How are you proceeding in your script or is it something to install at first to auto discover ? and finally, do we need oca_dependencies.txt ?

Best Regards,

**Comment by remi-filament** [comment]
Hi @kamarya sorry I did not see your issue before, I do not know why I was not notified...
As mentioned in README, we are not maintaining this repo anymore, we moved to our own Gitlab instance here : https://sources.le-filament.com/lefilament/odoo_docker

(also because DockerHub free plans do not allow for automatic generation of images anymore, so we do it in our Gitlab CI)

You will see there that we changed a bit the structure of the repo (with one branch per Odoo version).
Also, the Dockerfile is updated when needed, and you will find that v14 Dockerfile does not contain anymore these comments.

**Comment by remi-filament** [comment]
Hi @yboujraf this image is mainly used as base image for our deployments (meaning that we generate another image from this one to add any extra module / pip package necessary for each deployment context).

You can find more information in our Ansible role for deploying Odoo here : https://sources.le-filament.com/lefilament/ansible-roles/docker_odoo/
I am not sure whether you are familiar with Ansible but instructions are in tasks directory, and in templates you will find all the source files we use for deployment : 
- Dockerfile for generating derivated image from the one in DockerHub
- repos-addons.yaml and repos.yaml for listing all modules / repo to be installed
- fetch_repos and fetch_repos_addons to collect these modules
- prod.yaml and test.yaml are docker-compose for deploying both production and test Odoo environment
- odoo.conf for overriding default odoo.conf from this base image

Our point of view on dependencies (whether python or Odoo modules ones) are that we want to be sure of what we deploy on each server, so we do not have automatic dependency discovering, we expect all dependencies to be defined in Ansible variables to be added in the generated image.

Let me know if you need more information / guidance on these topics.
I will close this issue in the meantime if you do not mind.

**Comment by yboujraf** [comment]
Dear @remi-filament 

Yes i need some assistance to install your image.
Not yet familiar with Ansible because I just finished to learn Docker.

I am using usually VM and using bash script to install odoo and addons with success.
Now, I expect to use docker & Ansible.

So if you have a short description how to proceed will be fine for my fisrt stage.

Best Regards

**Comment by remi-filament** [comment]
Basically, 
you first have to install ansible (using pip install ansible for instance)
you can then clone this repo : https://github.com/lefilament/ansible
You then need to create your server in both host_vars (you can use Templates to set various variables needed) and inventory file.

You can install necessary package on your server using (if Debian based): 
anisble-playbook -i inventory_filament.inv  initial-playbook.yml --skip-tags raw-redhat

You could then be able to deploy docker using :
ansible-playbook -i inventory_filament.inv filament-playbook.yml -t docker

and then Odoo with : 
ansible-playbook -i inventory_filament.inv filament-playbook.yml -t docker_odoo

I will be off until beginning of January so not available for asking any question you may have in the mean time !
I wish you a good end of year period !

**Comment by yboujraf** [comment]
Merci

Wishe you all the best

**Comment by yboujraf** [comment]
Dear @remi-filament 

All the best crossing your path for 2022.

I am back to you regarding the odoo docker installation.

Is there a way to provide some support (we speak french) ?

Best Regards,
