### ISSUE TITLE
Support for odoo 15?

### ISSUE THREAD

**Issue by ni-ka** [lefilament/odoo_docker#3]
Hi @remi-filament 

Thanks again for the great work! Are you planning to migrate some of your tools to odoo 15?

Best regards

**Comment by remi-filament** [comment]
Hi @ni-ka, thanks for your words !
We are integrating only even versions of Odoo (otherwise we have to many to maintain) so we do not plan to generate Docker image for v15, next one should be for v16 (ETA end 2022).
Anyhow, it should not be much effort to generate image for v15 but since we would not deploy it, we will not maintain it and we could not check whether if works properly or not so I prefer not to go this way, but can help you if needed on your side ?

By the way, we are seldomly using github nowadays, most up to date repos are on our own Gitlab instance here : https://sources.le-filament.com/lefilament/odoo_docker (same applies for Ansible roles).

I let you close this issue if I answered your point (even if probably not what you expected...)

Best Regards !

**Comment by ni-ka** [comment]
Thanks @remi-filament its very helpful! For me its mostly about knowing that this project will be maintained in future.
